const pertanyaan1 = 'Apa saja organ reproduksi laki-laki';
const pertanyaan2 = 'Apa saja organ reproduksi perempuan';
const pertanyaan3 = 'Bagaimana menjaga kebersihan organ reproduksi';
const pertanyaan4 = 'apa itu pubertas';
const pertanyaan5 =
    'Apa perubahan secara umum pada remaja laki-laki dan perempuan yang terjadi saat pubertas?';
const pertanyaan6 =
    'Apa perubahan fisik secara khusus terjadi pada remaja perempuan saat pubertas?';
const pertanyaan7 =
    'Apa perubahan fisik secara khusus terjadi pada remaja laki-laki saat pubertas?';
const pertanyaan8 = 'Apa itu menstruasi?';
const pertanyaan9 = 'Bagaimana proses menstruasi?';
const pertanyaan10 = 'Apa yang harus dilakukan saat menstruasi';
const pertanyaan11 = 'Apa itu mimpi basah?';
const pertanyaan12 = 'Bagaimana proses terjadinya mimpi basah?';
const pertanyaan13 = 'Apa itu seks?';
const pertanyaan14 = 'Apa itu seksualitas?';
const pertanyaan15 = 'Apa itu orientasi seksual?';
const pertanyaan16 = 'Apa akibat seks sebelum menikah pada remaja?';
const pertanyaan17 = 'Bagaimana proses tejadinya kehamilan?';
const pertanyaan18 = 'Apa itu hubungan seksual?';
const pertanyaan19 = 'Bagaimana kehamilan yang berisiko?';
const pertanyaan20 = 'Bagaimana menghindari empat kondisi kehamilan berisiko?';
const pertanyaan21 = 'Apa itu stunting?';
const pertanyaan22 = 'Apa faktor terjadinya stunting?';
const pertanyaan23 = 'Apa itu hubungan seksual?';
const pertanyaan24 = 'Apa ciri-ciri stunting?';
const pertanyaan25 = 'Apa saja sumber gizi yang baik bagi remaja?';
const pertanyaan26 =
    'Apa gangguan kesehatan yang terjadi terkait dengan gizi remaja?';
const pertanyaan27 = 'Apa itu bullying?';
const pertanyaan28 = 'Apa saja bentuk Tindakan bullying?';
const pertanyaan29 = 'Apa itu kekerasan seksual?';
const pertanyaan30 = 'Bagaimana menghindari kekerasan seksual?';
const pertanyaan31 = 'Apa itu IMS?';
const pertanyaan32 = 'Apa gejala-gejala IMS?';
const pertanyaan33 = 'Apa itu HIV/AIDS?';
const pertanyaan34 = 'Apa gejala HIV/AIDS?';
const pertanyaan35 = 'Apa risiko Kesehatan terhadap perkawinan remaja?';
const pertanyaan36 = 'Berapa usia ideal untuk menikah?';

// jawaban

const jawaban1 =
    'PENIS\n\nOrgan laki-laki untuk berhubungan seksual. Penis menyemburkan sperma di dalam vagina pada saat hubungan seksual. Saat seorang laki-laki terangsang atau penisnya terstimulasi, penisnya menjadi besar (ereksi) dan berejakulasi agar semen dapat keluar. Jika sperma bertemu dengan telur di dalam tubuh perempuan, perempuan akan menjadi hamil.\n\nGLANS\n\nBagian depan atau kepala penis. Kulit yang menutupi bagian glans disebut foreskin (preputium) atau kulup. Sunat adalah memotong bagian kulup.\n\nSKROTUM\n\nStruktur ini berupa kantung yang melingkari dan melindungi serta tempat bergantungnya testis. Skrotum juga berfungsi mengontrol suhu yang tepat untuk produksi sperma dan kebertahanannya.\n\nTESTIS\n\nStruktur berbentuk oval dan biasanya terdapat dua buah di dalam skrotum. Testis merupakan tempat memproduksi dan menyimpan sperma sejak pubertas, dan memproduksi hormon seksual laki-laki, yaitu testosteron.\n\nKELENJAR PROSTAT DAN VESIKULA SEMINALIS\n\nKedua struktur ini terletak pada dasar kandung dan memproduksi cairan mani yang membawa sperma ke testis.\n\nVAS DEFERENS\n\nSaluran yang menyalurkan sperma dari testis menuju ke prostat. Sperma adalah sel seksual laki-laki; terlalu kecil untuk dilihat tanpa mikroskop; berbentuk seperti kecebong; bergerak dengan bantuan ekor mereka. Produksi umumnya dimulai pada rentang usia 12 hingga 24 tahun. Total yang dikeluarkan setiap ejakulasi adalah 200 hingga 50 juta sperma, tapi hanya satu yang dapat membuahi sebuah telur. Semen, yang merupakan cairan yang mengandung sperma, dikeluarkan penis di saat ejakulasi.\n\nURETHRA\n\nSaluran untuk mengeluarkan air seni dan air mani. tertutup saat terjadi ejakulasi.';
const jawaban2 =
    'VULVA\n\nBerbentuk segitiga terbalik yang terletak pada daerah dasar panggul. Vulva terdiri dari mons pubis dan labia mayora dan labia minora.\n\nMONS PUBIS\n\nBerada di bagian puncak vulva tepat pada tulang kemaluan (pubis). Struktur ini terbentuk dari lemak yang tertutup kulit dengan rambut kasar yang nyata pada wanita dewasa.\n\nKLITORIS\n\nOrgan kecil pada bagian depan vulva dan sangat sensitif bila disentuh titik pusat stimulasi; memberikan perasaan kepuasan saat distimulasi.\n\nLABIA MAYORA\n\nBibir vagina bagian luar, lipatan terluar di bagian bawah dari mons, berfungsi memberikan perlindungan kepada klitoris, lubang kencing, dan lubang vagina.\n\nLABIA MINORA\n\nBibir vagina bagian dalam, lipatan terdalam di bagian bawah mons. Ukurannya lebih kecil dari pada labia mayora.\n\nVAGINA\n\nBerbentuk pipih yang terbentuk dari otot. Vagina tidak dapat dilihat dari luar. Merupakan penghubung antara rahim dan bagian luar tubuh. Vagina berfungsi sebagai tempat seorang laki-laki memasukkan penisnya saat melakukan hubungan seksual, tempat keluarnya darah menstruasi dan sebagai jalan lahir bayi ketika persalinan.\n\nUTERUS(RAHIM)\n\nMenyerupai buah pir yang menjadi tempat tumbuhnya janin dalam kehamilan. Uterus tumbuh ketika pubertas dan mengalami perubahan dalam kehamilan. Ujung bawah uterus yang mengerucut disebut cervix atau leher rahim. Pada masa/periode subur, dinding rahim akan menebal dan berisi pembuluh darah sebagai persiapan tumbuhnya janin, namun jika tidak terjadi kehamilan akan luruh dan keluar sebagai menstruasi.\n\nCERVIX (LEHER RAHIM)\n\nBagian bawah dan terluar dari uterus atau rahim, sebagai batas penis waktu masuk ke dalam vagina. Pada saat persalinan, leher rahim membuka sehingga bayi dapat keluar.\n\nTUBA FALLOPII\n\nMerupakan saluran di kiri dan kanan rahim yang berfungsi sebagai saluran sel telur dari ovarium menuju uterus (proses ovulasi) dan tempat pembuahan (konsepsi) atau bertemunya sel telur (ovum) dan sperma. Ujung dari tuba fallopi adalah fimbrae yang  menangkap ovum yang dikeluarkan ovarium.\n\nOVARIUM (INDUNG TELUR)\n\nBerbentuk oval yang terdapat di ujung tuba fallopii (sebelah kiri dan kanan), yang menghasilkan ovum (sel telur) dan hormon estrogen dan progesterone. Berisi 300,000 hingga 500,000 sel telur saat kelahiran; mulai melepaskan telur di saat pubertas. Ovum atau telur berukuran sebesar kepala jarum; jika tidak dibuahi, telur-telur itu akan akan diserap oleh jaringan. Biasanya dilepaskan setiap bulan; jika lebih dari satu telur dilepaskan, kembar fraternal (tidak identik) atau kelahiran ganda dapat terjadi.';
const jawaban3 =
    'Perempuan\n\na)	Bersihkan organ reproduksi luar dari depan ke belakang, gunakan air bersih, dan dikeringkan menggunakan handuk atau tisu.\nb)	Tidak perlu membasuh bagian dalam vagina/kemaluan karena dapat mengganggu keseimbangan kimia pada bagian itu sehingga meningkatkan risiko infeksi.\nc)	Tidak boleh mencuci vagina dengan cairan pembilas wanita.\nd)	Selama masa menstruasi, pembalut harus diganti berkala paling lama setiap empat jam sekali atau setiap setelah buang air kecil, untuk mempertahankan kebersihan.\ne)	Pemakaian panty liner tidak disarankan dalam waktu lama (lebih dari empat jam).\n\nLaki-laki\n\na)	Ketika tidak disunat: tarik kulit luar dari ujung penis dan cuci secara lembut daerah tersebut setiap habis berkemih.\nb)	Ketika sudah disunat: selalu cuci bersih penis setiap habis berkemih.';
const jawaban4 =
    'PUBERTAS adalah masa peralihan dari anak-anak menjadi dewasa (masa remaja), ditandai dengan matangnya organ reproduksi. Pubertas pada perempuan terjadi antara umur 8 – 13 tahun. Sedangkan pada laki-laki antara umur 9 – 14 tahun. Perempuan biasanya mulai pubertas satu atau dua tahun lebih cepat dari laki-laki.';
const jawaban5 =
    'PERUBAHAN FISIK\n\na)	Tinggi badan bertambah dengan pesat \nb)	Berat badan bertambah \nc)	Wajah menjadi lebih berisi\nd)	Kulit menjadi lebih berminyak\ne)	Keringat bertambah banyak\nf)	Muncul jerawat pada wajah\ng)	Tubuh mulai berbulu\n\nPERUBAHAN PSIKIS\n\na)	Perubahan psikis akibat perubahan fisik \nb)	Perubahan mood dan emosi \nc)	Krisis identitas diri \nd)	Lebih senang bergabung dengan teman mereka\ne)	Menjadi lebih sensitif: lebih emosi dan sangat mudah tersinggung\nf)	Merasa aneh dengan bentuk tubuh dan merasa bingung\ng)	Dorongan hormon akan mendorong perasaan seksual sehingga mulai tertarik kepada lawan jenis\nh)	Ingin menjadi diri sendiri';
const jawaban6 =
    'a)	Bentuk tubuh menjadi sedikit bulat karena lemak mulai menumpuk \nb)	Pinggul melebar \nc)	Payudara mulai membesar \nd)	Puting mulai menonjol \ne)	Tumbuh rambut-rambut halus di sekitar ketiak dan alat kelamin (pada beberapa remaja perempuan juga tumbuh rambut sedikit di lengan dan tungkai) \nf)	Warna alat kelamin menjadi agak gelap dan mulai berotot \ng)	Mulai menstruasi';
const jawaban7 =
    'a)	Bahu dan dada bertambah lebar \nb)	Tubuh menjadi lebih berotot bertambah berat dan tinggi\nc)	Tumbuh jakun\nd)	Suara pecah dan menjadi lebih dalam \ne)	Tumbuh rambut-rambut halus di sekitar ketiak dan alat kelamin (pada sebagian remaja laki-laki juga tumbuh rambut di lengan, tungkai, dada, punggung, dan wajah: kumis dan janggut) \nf)	Penis dan skrotum menjadi lebih besar dan berwarna gelap\ng)	Dapat terjadi ejakulasi (keluarnya air mani) di antaranya melalui mimpi basah.';
const jawaban8 =
    'Menstruasi (di Indonesia juga kadang disebut sebagai “mens” atau juga “datang bulan” karena terjadi setiap bulan) merupakan salah satu tanda bahwa seorang perempuan telah memasuki masa pubertas, ditandai dengan terjadinya peluruhan darah dari dinding rahim dan keluar melalui vagina.';
const jawaban9 =
    'Pada waktu tertentu di setiap bulan, pada perempuan yang sudah pubertas terjadi proses ovulasi. Proses ovulasi merupakan proses dimana ovarium atau indung telur menghasilkan sel telur atau ovum. Ketika sel telur matang, maka sel telur akan keluar dari ovarium dengan pecahnya folikel. Jika folikel sudah melepaskan sel telur, maka folikel akan berkembang dengan membentuk korpus luteum. Korpus luteum ini akan melepaskan hormon untuk membantu menebalkan lapisan rahim yang akan mempersiapkan segala sesuatu jika sebuah proses kehamilan terjadi. Setelah folikel melepaskan sel telur, maka ia akan berjalan menuju tuba falopi. Sel telur ini akan tinggal di tuba falopi selama 24 jam untuk menunggu sel sperma membuahinya. Sel telur hanya memiliki waktu sekitar 12 sampai 24 jam untuk bertahan di tuba falopi, Jika sel telur tidak dibuahi atau tidak ada sperma yang berhasil menuju tuba falopi, maka sel telur akan bergerak menuju rahim, kemudian hancur. Kadar hormon yang telah dihasilkan oleh korpus luteum akan kembali menjadi normal sehingga lapisan rahim yang tadinya menebal, maka akan meluruhkan darah dari dinding rahim yang kita sebut dengan menstruasi.';
const jawaban10 =
    '1)	Mandi setiap hari.\n1)	Mandi setiap hari.\n3)	Gunakan kain bersih, pembalut, atau material lain yang bersih atau dapat diganti, dan ganti dengan rutin agar darah menstruasi tidak muncul di pakaian. \n4)	Kebersihan merupakan hal penting untuk mencegah infeksi. Cuci baju dengan sabun dan keringkan di bawah matahari untuk mencegah adanya bakteri. \n5)	Beristirahat cukup. \n6)	Lanjutkan kegiatan seperti biasa. \n7)	Jika mengalami keram atau terasa sakit di bawah perut atau punggung, lakukan aktivitas berikut untuk menjadi lebih nyaman: mandi air hangat, minum minuman panas, berjalanjalan, pijat bagian bawah perut, berbaring dengan menaikkan lutut dan menggerakkannya di dalam lingkaran kecil. \n8)	Berolahraga. Olahraga mempercepat sirkulasi dan mengurangi ketegangan atau sakit kepala. \n8)	Berolahraga. Olahraga mempercepat sirkulasi dan mengurangi ketegangan atau sakit kepala. \n10)	Terkadang bahwa selama kurang lebih satu minggu sebelum menstruasi, perempuan dapat mengalami beberapa hal berikut: payudara yang terasa sakit, suasana hati yang berubah-ubah, mengidam makanan. Perubahan-perubahan ini adalah hal yang biasa terjadi.';
const jawaban11 =
    'Mimpi basah atau nocturnal emission merupakan pengeluaran air mani atau sperma (ejakulasi) yang terjadi saat tidur. Hal ini normal terjadi pada anak laki-laki yang memasuki masa pubertas, yaitu pada usia 10 – 12 tahun. Lebih dari 70 persen laki-laki di dunia mengalami mimpi basah.';
const jawaban12 =
    'Saat seorang laki-laki memasuki masa pubertas, maka hormon testosteron mulai berfungsi dan sepasang testis (buah zakar) akan terus menerus menghasilkan sperma hingga seumur hidup. Sperma yang sudah matang akan disalurkan melalui saluran sperma atau vas deferens menuju urethra (saluran kencing). Dalam perjalanannya menuju urethra, ratusan juta sperma akan bercampur dengan cairan sperma atau air mani yang dihasilkan oleh prostat dan kelenjar seminalis (cairan mani ini berfungsi memberi makanan kepada sperma), dan keluar melalui saluran kencing (urethra). Pada umumnya sel sperma yang matang akan bertahan dalam waktu 4 minggu. Sperma yang matang yang bercampur dengan cairan mani disiapkan secara otomatis (alamiah) oleh tubuh pada seorang laki-laki untuk proses reproduksi. Jika terjadi hubungan seksual dengan seorang perempuan, sel sperma ini akan bertemu dengan sel telur pada perempuan dan sudah mampu untuk membuahinya sehingga akan terjadi kehamilan. Jika tidak terjadi hubungan seksual, sel sperma ini akan keluar dengan sendirinya melalui mimpi basah. Keluarnya air mani yang mengandung sperma ini disebut ejakulasi. Ejakulasi yang tanpa rangsangan yang nyata disebut mimpi basah.';
const jawaban13 =
    'Seks adalah jenis kelamin. Perbedaan biologis yang dimiliki laki-laki dan perempuan. Perbedaan biologis tersebut dapat dilihat sejak lahir dan pada masa pertumbuhan. Misalnya laki-laki memiliki penis dan perempuan memiliki vagina; perempuan memiliki rahim dan laki-laki memiliki testis. Selain seks, saat ini juga ada istilah identitas gender: bagaimana seseorang berpikir tentang dirinya, apakah laki-laki, perempuan, waria atau priawan.';
const jawaban14 =
    'Seksualitas adalah bagian dari diri manusia mengenai jenis kelaminnya, identitas gender dan peran, orientasi seksual, erotisme, kenikmatan, kemesraan, dan reproduksi (WHO, 2006). Seksualitas adalah hal-hal yang dirasakan dan diekspresikan melalui pikiran, fantasi, hasrat, kepercayaan, perilaku, nilai, sikap, praktik serta peran dan hubungan. Seksualitas mencakup perilaku seksual, perasaan, identitas gender serta peran seksual, orientasi seksual, dan reproduksi. Hal tersebut merupakan bagian dari seksualitas namun seksualitas belum tentu harus dirasakan dan diekspresikan. Seksualitas dipengaruhi oleh beberapa faktor, diantaranya fisik, psikologis, spiritual, dan budaya.';
const jawaban15 =
    'Orientasi seksual adalah ketertarikan seseorang kepada orang lain secara fisik dan emosional. Setiap manusia memiliki orientasi seksual yang berbeda, antara lain:\n\na)	Heteroseksual: jika seseorang tertarik pada lain jenis kelamin; \nb)	Homoseksual: jika seseorang tertarik pada sesama jenis kelamin;\nc)	Biseksual: jika seseorang tertarik pada kedua jenis kelamin sekaligus.';
const jawaban16 =
    '1.	Perasaan berdosa\n2.	Berpotensi terjadi kehamilan yang tidak diinginkan (KTD)\n';
const jawaban17 =
    'Kehamilan berkaitan erat dengan organ, sistem, dan fungsi reproduksi. Kehamilan merupakan proses alamiah yang terjadi para perempuan yang sudah menikah. Meskipun terjadi pada perempuan, kehamilan sangat berkaitan dengan laki-laki. Agar dapat hamil, seorang wanita memerlukan sel telur, rahim yang sehat, serta sperma yang dihasilkan laki-laki untuk membuahi sel telur tersebut. Oleh karena itu, kehamilan terjadi karena beberapa hal, yaitu: (1) adanya sel sperma; (2) adanya sel telur (ovum); (3) hormonal normal dan anatomi; (4) proses pembuahan; dan (5) nidasi atau implantasi/bersarangnya sel telur dan sperma yang sudah melalui proses pembuahan pada dinding rahim.';
const jawaban18 =
    'Hubungan seksual adalah dimasukkannya penis ke dalam vagina. Saat seorang perempuan dan laki-laki berhubungan seksual, berjuta-juta sperma akan diejakulasikan dari penis ke dalam vagina. Sperma yang telah dikeluarkan akan berenang ke atas vagina menuju uterus dan melalui tuba fallopi untuk mencari sebuah telur. Jika terdapat telur yang matang, pembuahan dapat terjadi. Walaupun ada berjuta-juta sperma, hanya satu yang dapat membuahi telur yang matang. Telur yang telah di dibuahi bergerak melalui tuba falopi dan menempel di uterus, di mana janin akan bertumbuh. Jika telur tidak dibuahi, menstruasi akan terjadi.';
const jawaban19 =
    '1.	Terlalu Muda\n2.	Terlalu tua\n3.	Terlalu dekat atau rapat jarak antarkehamilan\n4.	Terlalu sering/banyak';
const jawaban20 =
    'Memiliki perencanaan reproduksi yang sesuai dengan Fase Reproduksi Sehat. Fase Reproduksi Sehat merupakan suatu masa/waktu/periode tertentu yang baik untuk merencanakan kehamilan (lihat gambar Fase Perencanaan Kehamilan Terbaik). Rencana reproduksi paling baik bagi perempuan adalah MENUNDA PERKAWINAN HINGGA USIA IDEAL, namun apabila gagal maka diupayakan MENUNDA KEHAMILAN ANAK PERTAMA hingga mencapai usia 21 tahun.';
const jawaban21 =
    'Stunting merupakan suatu kejadian kurang gizi yang banyak terjadi di seluruh dunia. Stunting terjadi akibat dari kekurangan nutrisi dalam jangka waktu yang lama. Penyebab awal dari stunting adalah kekurangan asupan energi dan protein.';
const jawaban22 =
    'a)	Faktor dasar: berasal dari ibu, yaitu usia, postur tubuh, dan kondisi Kesehatan fisik dan psikososial, serta status gizi\nb)	Faktor kateristik rumah tangga: tingkat kesejahteraan rumah tangga, status sosial, Pendidikan orang tua, pekerjaan orang tua, dan penentu keputusan dalam rumah tangga\nc)	Faktor karakteristik wilayah: lokasi, produksi dan distribusi makanan, pertumbuhan populasi pada wilayah tersebut.';
const jawaban23 =
    'Tinggi badan yang lebih pendek dibanding tingga badan anal lain pada umumnya atau yang seusia.';
const jawaban24 =
    '1.	Anak mudah sakit\n2.	Postur tubuh kecil Ketika dewasa\n3.	Menyebabkan kematian pada usia dini\n4.	Otak sulit berkembang; memengaruhi kecerdasan anak. Anak akan sulit belajar dan menyerap infomasi.';
const jawaban25 =
    '1.	SUMBER ENERGI (sumber tenaga): karbohidrat (beras, jagung, umbi-umbian, mie, kentang, roti, minyak, mentega, dan santan yang mengandung lemak)\n2.	SUMBER PROTEIN (zat pembangun): sumber hewani (daging, ayam, ikan, telur), sumber nabati (kacang-kacangan, biji-bijian, tahu, tempe). Zat ini diperlukan untuk pertumbuhan, perkembangan badan, pembentukan jaringan baru dan pemeliharaan tubuh.\n3.	LEMAK : minyak goreng, mentega, susu, daging, ikan. Namun makanan berlemak seperti gajih, kulit, susu berlemak disarankan untuk tidak dikonsumsi berlebihan, karena dapat mengganggu kesehatan. \n4.	VITAMIN (zat pengatur): sayuran dan buah-buahan. Vitamin yang diperlukan antara lain vitamin B6, asam folat, B12, A, C, D dan E. \n5.	MINERAL : diperlukan untuk pertumbuhan dan perkembangan selama masa pubertas. Kalsium: susu/makanan hasil olahan susu (keju), makanan yang difermentasi (tempe, oncom, tauco). Sumber Zn (seng) : ikan, kerang, sayuran.\n';
const jawaban26 =
    '1.	Anemia\n\nGejala:\n\na)	Mudah lelah \nb)	Sulit tidur \nc)	Kurang/hilang nafsu makan \nd)	Sulit berkonsentrasi \ne)	Lemah/lesu \nf)	Pusing dan mata berkunang-kunang terutama ketika bangkit dari duduk\n\n2.	Kelainan pola makan\n\na)	ANOREXIA NERVOSA. Penyakit yang umumnya diderita oleh remaja putri (walaupun laki-laki juga dapat mengalaminya).\nb)	BULIMIA. Serupa dengan anorexia nervosa, namun penderita bulimia SANGAT TAKUT MENJADI GEMUK.';
const jawaban27 =
    'BULLYING merupakan salah satu tindakan agresi/serangan yang dilakukan satu orang dengan tujuan untuk menyakiti atau mengganggu orang lain atau korban yang lebih lemah darinya. Mereka yang menjadi korban bullying kemungkinan akan menderita depresi dan kurang percaya diri, yang pada akhirnya korban bullying menjadi kesulitan dalam bergaul.';
const jawaban28 =
    'a)	BULLYING DALAM BENTUK FISIK: memukul, mendorong, mengancam secara fisik, memelototi, dan mencuri barang. \nb)	BULLYING DALAM BENTUK PSIKOLOGIS: pelecehan seksual, mengucilkan, menyebarkan gosip, mengancam, gurauan yang mengolok-ngolok dan mengasingkan seseorang secara sosial.\nc)	BULLYING DALAM BENTUK VERBAL: hinaan, bentakan, menggunakan kata-kata kasar, menyindir, memanggil dengan julukan, dan dipaksa melakukan telepon bertema seksual/phone sex dll.\nd)	CYBERBULLYING. Di era serba modern seperti sekarang ini bahkan tindakan bullying juga menjadi “terfasilitasi” dengan gadget dan media sosial (cyberbullying).';
const jawaban29 =
    'KEKERASAN SEKSUAL adalah setiap tindakan, baik berupa ucapan ataupun perbuatan, yang dilakukan seseorang untuk menguasai atau memanipulasi orang lain serta membuatnya terlibat dalam aktivitas seksual yang tidak dikehendaki.';
const jawaban30 =
    'a)	Tanamkan pada diri sendiri bahwa: “TUBUH KITA MERUPAKAN MILIK PRIBADI YANG BERHARGA”. \nb)	TIDAK SEMUA ORANG BOLEH MENYENTUH BAGIAN PRIBADI seperti alat kelamin dan dada, kecuali pada saat tertentu seperti saat sedang diperiksa oleh dokter. \nc)	Bedakan ‘SENTUHAN BOLEH’ dan ‘SENTUHAN TIDAK BOLEH’. ‘SENTUHAN BOLEH’ didasarkan niat baik seperti ibu membelai kepala anak. ‘SENTUHAN TIDAK BOLEH’ sering dihubungkan dengan niat yang menuju ke arah seksual, seperti memegang dada, alat kelamin, atau bokong. \nc)	Bedakan ‘SENTUHAN BOLEH’ dan ‘SENTUHAN TIDAK BOLEH’. ‘SENTUHAN BOLEH’ didasarkan niat baik seperti ibu membelai kepala anak. ‘SENTUHAN TIDAK BOLEH’ sering dihubungkan dengan niat yang menuju ke arah seksual, seperti memegang dada, alat kelamin, atau bokong. \ne)	Biasakan budaya malu dengan TIDAK MEMPERLIHATKAN AURAT kepada orang lain, seperti berpakaian yang sopan. \nf)	SEGERA MELAPOR ke orang terdekat dan dipercaya apabila melihat atau mengalami peristiwa yang tidak diinginkan.';
const jawaban31 =
    'Infeksi Menular Seksual (IMS) adalah infeksi yang ditularkan dari orang ke orang melalui hubungan seksual atau kontak alat kelamin. IMS dapat disebabkan oleh virus, bakteri, parasit atau jamur yang hanya dapat dilihat melalui alat pembesar (mikroskop) karena sangat kecil, tidak dapat dilihat oleh mata. Penyakit yang serius dan menyakitkan ini mempengaruhi organ reproduksi dan seksual serta dapat menyebabkan infertilitas atau ketidaksuburan, keguguran, dan gagal bersalin.';
const jawaban32 =
    'a)	Keluarnya cairan yang tidak normal dari saluran kencing atau liang senggama (keputihan yang banyak sekali, berbau amis, berwarna putih kekuning-kuningan atau putih kehijauan). Contoh IMS dengan gejala tersebut adalah gonore, trikomonas, jamur. \nb)	Rasa nyeri/sakit pada saat kencing atau saat berhubungan seksual. Contoh IMS dengan gejala tersebut adalah gonore. \nc)	Rasa gatal di alat kelamin atau sekitarnya. Contoh IMS dengan gejala tersebut adalah jamur, trikomonas. \nd)	Lecet, luka kecil (kadang-kadang ada yang tidak terasa sakit) yang disertai dengan pembengkakan kelenjar getah bening. Contoh IMS dengan gejala tersebut adalah sifilis, chancroid.';
const jawaban33 =
    'Acquired Immune Deficiency Syndrom (AIDS) disebabkan oleh Human Immunodeficiency Virus (HIV) yang merusak kekebalan tubuh, yang membuat tidak dapat melawan penyakit berat maupun ringan. Jadi AIDS adalah kumpulan gejalanya, HIV adalah virus yang menyebabkan AIDS. HIV hanya dapat hidup di dalam sel tubuh manusia yang didapat atau tertular atau terinfeksi virus HIV. HIV dapat hidup di dalam darah, cairan vagina, cairan sperma dan air susu ibu. HIV / AIDS perlu mendapat perhatian khusus, karena belum dapat disembuhkan. ';
const jawaban34 =
    'a)	Penurunan 10% berat badan dalam waktu satu bulan tanpa sebab yang jelas\nb)	Diare lebih dari satu bulan tanpa sebab yang  jelas\nc)	Demam berkepanjangan lebih dari satu bulan\nd)	Batuk yang tidak sembuh-sembuh\ne)	Kulit gatal di seluruh tubuh\nf)	Infeksi jamur kandida pada mulit, lidah atau tenggorokan\ng)	Pembengkakan kelenjar getah bening di leher, ketiak atau selangkangan';
const jawaban35 =
    'a)	Tekanan darah tinggi, risiko yang lebih berat mungkin akan terjadi yaitu eklampsia (kejang-kejang)\na)	Tekanan darah tinggi, risiko yang lebih berat mungkin akan terjadi yaitu eklampsia (kejang-kejang)\nc)	Bayi kekurangan berat badan atau Berat Badan Lahir Rendah (BBLR)\nc)	Bayi kekurangan berat badan atau Berat Badan Lahir Rendah (BBLR)\ne)	Proses persalinan yang memakan waktu lama\nf)	Kematian ibu dan janin';
const jawaban36 =
    'Usia ideal untuk menikah pada laki-laki adalah 25 tahun, dengan pertimbangan perannya sebagai suami, laki-laki sudah memiliki pertimbangan keuangan dengan memiliki pendapatan atau penghasilan untuk memenuhi kebutuhan keluarga. Sementara, usia ideal untuk menikah pada  perempuan ialah 21 tahun, karena berkaitan dengan kesiapan fisik, terutama untuk hamil dan melahirkan, mental, emosi dan kesiapan lainnya.';
